name: 更新 Proxy

# 指定本工作流运行所需的权限
permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/UpProxy.js"  # 当此文件变动时触发
  schedule:
    - cron: "*/10 * * * *"  # 每10分钟运行一次
  workflow_dispatch:       # 支持手动触发

jobs:
  UpProxy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v3

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 安装依赖
        run: npm install axios adm-zip moment-timezone

      - name: 运行更新 Proxy 脚本
        run: node .github/workflows/UpProxy.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
